create table "budget" (
  "name" VARCHAR(254) NOT NULL,
  "description" TEXT,
  "_id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY
);

create table "account" (
  "name" VARCHAR(254) NOT NULL,
  "_budgetId" BIGINT NOT NULL,
  "_id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY
);

alter table
  "account"
add
  constraint "budget_fk" foreign key("_budgetId") references "budget"("_id") on update NO ACTION on delete NO ACTION;

create table "payment" (
  "name" VARCHAR(254) NOT NULL,
  "description" TEXT,
  "amount" NUMERIC(15, 2) NOT NULL,
  "_accountId" BIGINT NOT NULL,
  "_id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY
);

alter table
  "payment"
add
  constraint "account_fk" foreign key("_accountId") references "account"("_id") on update NO ACTION on delete NO ACTION
