version: '3'

services:
  traefik:
    image: "traefik:2.1"
    command:
      - "--log.level=info"
      - "--api.insecure=true"
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
    ports:
      - "9000:80"     # The HTTP port
      - "9080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
    restart: on-failure
  mongo:
    image: "mongo:4.2.5"
    restart: on-failure
    ports:
      - "27017:27017"
    volumes:
      - mongo_db:/data/db
    labels:
      - "traefik.enable=false"
  admin_mongo:
    image: "mongo-express"
    restart: on-failure
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_SITE_BASEURL=/mongo/
      - VCAP_APP_HOST=0.0.0.0
    labels:
      - "traefik.http.routers.admin-mongo.rule=PathPrefix(`/mongo`)"
  user-svc:
    image: hobbypunk90/mt-services-user:fa26b3d
    # ports:
    #   - 9012:3000
    depends_on:
      - mongo
    environment:
      - RAILS_MASTER_KEY=ee58f8f3dfb3b3fd40391087bfd38c4e
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    volumes:
      - ./config/user-svc.settings.yml:/config.yml
    labels:
      - "traefik.http.routers.user-svc.rule=PathPrefix(`/api/v{[0-9]+}/users`)"
  auth-svc:
    image: hobbypunk90/mt-services-auth:0.0.3
    # ports:
    #   - 9013:3000
    depends_on:
      - mongo
      - user-svc
    environment:
      - RAILS_MASTER_KEY=f84a1e93cf144b98ded39b233d03b60f
      - RAILS_ENV=development
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - USER_SERVICE_HOST=user-svc
      - USER_SERVICE_PORT=3000
      - USER_SERVICE_PROTOCOL=http
      #- LOGIN_REDIRECT_URI=http://localhost:9000/
    volumes:
      - ./config/auth-svc.settings.yml:/config.yml
    labels:
      - "traefik.http.routers.auth-svc.rule=PathPrefix(`/api/v{[0-9]+}/auths`)"

volumes:
  budget-planner-db:
  mongo_db:
